add section we will call you (html)
LazebnyiDanylo/project-shift pull request #3
Opened 2023-06-30 18:22 UTC by KatiaOcheretiana

2023-06-30 20:17 UTC, LazebnyiDanylo requested changes
input заверни в label и убери pattern, он не нужен. в div.recall-img можно было сразу добавить тег img

2023-07-01 06:34 UTC, KatiaOcheretiana commented
Додала img та label.  
pattern необхідно по ТЗ

2023-07-01 12:40 UTC, LazebnyiDanylo requested changes
Фон і зображення окремо (спитав у ментора), зображення з прозорим фоном в  працює в png форматі

2023-07-01 13:16 UTC, KatiaOcheretiana commented
внесла зміни

2023-07-02 08:38 UTC, LazebnyiDanylo approved these changes

2023-07-02 08:42 UTC, DeadMakar approved these changes

2023-07-02 08:42 UTC, merged